--
-- MAME STATE OUTPUT PROJECT (MSOP)
-- MSOP MAME DATABASE DRIVER LUA
-- Script Version: 1.4.0
-- Script Date: 2026.07.20
-- Compiled Date: 2026.07.23
-- Project: https://github.com/djGLiTCH/MAME-LUA-SCRIPT-STATE-OUTPUTS
-- License: GNU GENERAL PUBLIC LICENSE GPL-v3.0
-- Copyright (c) 2026 Jacob Simpson (DJ GLiTCH). All Rights Reserved.
--
-- Auto-generated by msop_native_outputs_compiler.py from a MAME source
-- checkout - DO NOT HAND-EDIT. Re-run that script to regenerate. Manual
-- additions belong in database.lua's own ADDITIONAL_OUTPUT_FORWARDS field
-- instead (see init.lua's Forward_Native_Outputs, which merges both).
--
-- The output names below were identified by scripted analysis of MAME's
-- own source code (https://github.com/mamedev/mame), a separate project
-- not affiliated with MSOP. MAME is free software distributed under the
-- GNU General Public License v2.0 or later; the large majority of
-- individual files, including the driver files this data was read from,
-- are separately licensed under the 3-Clause BSD License. Full license
-- terms: https://github.com/mamedev/mame/blob/master/COPYING - "MAME" is
-- a registered trademark of Gregory Ember, referenced here solely to
-- describe this data's source, not to imply endorsement or affiliation.
--

local native_outputs_by_rom = {
    ["alien3"] = {
        "Back_lamp",
        "Blue_Button_1P_lamp",
        "Blue_Button_2P_lamp",
        "Blue_Corner_lamp",
        "Entry_lamp",
        "1P_Start_lamp",
        "2P_Start_lamp",
        "3P_Start_lamp",
        "4P_Start_lamp",
        "5P_Start_lamp",
        "6P_Start_lamp",
        "lamp0",
        "lamp1",
        "Left_lamp",
        "Left_Winner_lamp",
        "Lights_lamp",
        "Start_lamp",
        "Winner_lamp",
        "Player1_Gun_Recoil",
        "Player2_Gun_Recoil",
        "Red_Button_1P_lamp",
        "Red_Button_2P_lamp",
        "Red_Corner_lamp",
        "Right_lamp",
        "Right_Winner_lamp",
        "Wiper_lamp",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5",
        "lamp6",
        "lamp7",
        "lamp8",
        "lamp9",
        "lamp10",
        "lamp11",
        "lamp12",
        "lamp13",
        "lamp14",
        "lamp15"
    },
    ["area51"] = {
    },
    ["area51mx"] = {
    },
    ["bbust2"] = {
        "wheel_motor",
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5",
        "lamp6",
        "lamp7"
    },
    ["bel"] = {
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5"
    },
    ["carnevil"] = {
        "wheel",
        "wheel_motor",
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5",
        "lamp6",
        "lamp7",
        "lamp8",
        "lamp9",
        "lamp10",
        "lamp11",
        "lamp12",
        "lamp13",
        "lamp14",
        "lamp15",
        "led0",
        "led1",
        "led2",
        "led3",
        "led4",
        "led5",
        "led6",
        "led7",
        "led8",
        "led9",
        "led10",
        "led11",
        "led12",
        "led13",
        "led14",
        "led15",
        "led16",
        "led17",
        "led18",
        "led19",
        "led20",
        "led21",
        "led22",
        "led23"
    },
    ["crszone"] = {
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5",
        "lamp6",
        "lamp7"
    },
    ["cryptklr"] = {
    },
    ["dragngun"] = {
    },
    ["dragngunj"] = {
    },
    ["duckhunt"] = {
    },
    ["hotd"] = {
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5"
    },
    ["invasnab"] = {
        "digit0",
        "digit1",
        "digit2",
        "digit3",
        "digit4",
        "digit5",
        "digit6",
        "led0",
        "led1",
        "led2",
        "led3",
        "led4",
        "led5",
        "led6",
        "led7",
        "led8",
        "led9",
        "led10",
        "led11",
        "led12",
        "led13",
        "led14",
        "led15",
        "led16",
        "led17",
        "led18",
        "led19",
        "led20",
        "led21",
        "led22",
        "led23",
        "led24",
        "led25",
        "led26",
        "led27",
        "led28",
        "led29",
        "led30",
        "led31",
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5",
        "lamp6",
        "lamp7"
    },
    ["jdredd"] = {
    },
    ["jpark"] = {
        "Back_lamp",
        "Blue_Button_1P_lamp",
        "Blue_Button_2P_lamp",
        "Blue_Corner_lamp",
        "Entry_lamp",
        "1P_Start_lamp",
        "2P_Start_lamp",
        "3P_Start_lamp",
        "4P_Start_lamp",
        "5P_Start_lamp",
        "6P_Start_lamp",
        "lamp0",
        "lamp1",
        "Left_lamp",
        "Left_Winner_lamp",
        "Lights_lamp",
        "Start_lamp",
        "Winner_lamp",
        "Player1_Gun_Recoil",
        "Player2_Gun_Recoil",
        "Red_Button_1P_lamp",
        "Red_Button_2P_lamp",
        "Red_Corner_lamp",
        "Right_lamp",
        "Right_Winner_lamp",
        "Wiper_lamp",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5",
        "lamp6",
        "lamp7",
        "lamp8",
        "lamp9",
        "lamp10",
        "lamp11",
        "lamp12",
        "lamp13",
        "lamp14",
        "lamp15"
    },
    ["le2"] = {
        "lamp0"
    },
    ["lethalen"] = {
    },
    ["lethalj"] = {
        "lamp0",
        "lamp1",
        "lamp2"
    },
    ["maxforce"] = {
    },
    ["opwolf"] = {
        "Player1_Recoil_Piston"
    },
    ["opwolf3"] = {
    },
    ["othunder"] = {
        "Player1_Recoil_Piston",
        "Player2_Recoil_Piston"
    },
    ["policetr"] = {
        "leds0",
        "leds1",
        "leds2",
        "leds3"
    },
    ["ptblank"] = {
    },
    ["sgunner"] = {
        "digit0",
        "digit1",
        "digit2",
        "digit3",
        "digit4",
        "digit5",
        "digit6",
        "digit7",
        "diorama0",
        "diorama1",
        "diorama2",
        "diorama3",
        "diorama4",
        "diorama5",
        "gun_recoil0",
        "gun_recoil1"
    },
    ["sgunner2"] = {
        "digit0",
        "digit1",
        "digit2",
        "digit3",
        "digit4",
        "digit5",
        "digit6",
        "digit7",
        "diorama0",
        "diorama1",
        "diorama2",
        "diorama3",
        "diorama4",
        "diorama5",
        "gun_recoil0",
        "gun_recoil1"
    },
    ["sgunner2j"] = {
        "digit0",
        "digit1",
        "digit2",
        "digit3",
        "digit4",
        "digit5",
        "digit6",
        "digit7",
        "diorama0",
        "diorama1",
        "diorama2",
        "diorama3",
        "diorama4",
        "diorama5",
        "gun_recoil0",
        "gun_recoil1"
    },
    ["sgunnerj"] = {
        "digit0",
        "digit1",
        "digit2",
        "digit3",
        "digit4",
        "digit5",
        "digit6",
        "digit7",
        "diorama0",
        "diorama1",
        "diorama2",
        "diorama3",
        "diorama4",
        "diorama5",
        "gun_recoil0",
        "gun_recoil1"
    },
    ["timecris"] = {
        "mcuout0",
        "mcuout1",
        "mcuout2",
        "mcuout3",
        "mcuout4",
        "mcuout5",
        "mcuout6",
        "mcuout7",
        "mcuout8",
        "mcuout9",
        "mcuout10",
        "mcuout11",
        "mcuout12",
        "mcuout13",
        "mcuout14",
        "mcuout15",
        "cpuled0",
        "cpuled1",
        "cpuled2",
        "cpuled3",
        "cpuled4",
        "cpuled5",
        "cpuled6",
        "cpuled7",
        "wheel_motor"
    },
    ["timecrs2"] = {
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5",
        "lamp6",
        "lamp7"
    },
    ["vcop"] = {
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5"
    },
    ["vcop2"] = {
        "lamp0",
        "lamp1",
        "lamp2",
        "lamp3",
        "lamp4",
        "lamp5"
    },
}

return native_outputs_by_rom
