name: Package Latest Scripts

on:
  workflow_dispatch:
  push:
    paths:
      - 'MAME/**'
      - 'Hook Of The Reaper/**'
      - 'MAMEhooker/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP archive
      run: |
        zip -r MAME-STATE-OUTPUT-PLUGIN-LATEST.zip MAME "Hook Of The Reaper" "MAMEhooker"

    - name: Move ZIP to Updater folder
      run: |
        mkdir -p Updater
        mv MAME-STATE-OUTPUT-PLUGIN-LATEST.zip Updater/

    - name: Commit and push the new ZIP
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-package latest plugin files into zip file"
        file_pattern: 'Updater/MAME-STATE-OUTPUT-PLUGIN-LATEST.zip'